Add a custom tasmod server managing tasmod packets
MinecraftTAS/TASmod-Experiments pull request #4
Opened 2022-02-05 21:11 UTC by MCPfannkuchenYT

A non-blocking tick-independent separate server used for all TASmod packets.

### What does it do
* Transfering packets between server and client without ... blocking the main thread
* ... being dependent to the tick cycle
* ... waiting for minecraft packets to process beforehand

### Why is it needed
* It is non-blocking
* It is tick-independant
* Less packet loss (possibly?)

2022-02-05 21:12 UTC, MCPfannkuchenYT commented
Sorry about the past 2 actions.
Please review code so far
@ScribbleLP

2022-02-05 21:36 UTC, ScribbleLP requested changes

2022-02-05 21:36 UTC, ScribbleLP commented on src/com/minecrafttas/tasmod/CommonTASmod.java
> +	 * net.minecraft.server.MinecraftServer.run()V
Add something like:  
`Implemented in: HookMinecraftServer#hookRunEvent() target=net.minecraft.server.MinecraftServer.run()V` To show where it is implemented to indicate to the jadocs that it is there...

2022-02-05 21:36 UTC, ScribbleLP commented on src/com/minecrafttas/tasmod/mixin/events/HookMinecraftServer.java
> +	 * Triggers an Event in {@link CommonTASmod#onServerTick(Minecraft)} once the server starts
> onServerTick 

Wrong name of the method in CommonTASmod

2022-02-05 21:36 UTC, ScribbleLP commented on src/com/minecrafttas/tasmod/CommonTASmod.java
> +	 * Initialize the TASmod on the launching integrated or dedicated server.
> Initialize the TASmod on the launching integrated or dedicated server.  

Typo, `on launching the`

2022-02-05 21:36 UTC, ScribbleLP commented on src/com/minecrafttas/tasmod/client/ClientTASmod.java
> +	public void onClientConnect(ClientConnectedToServerEvent e) {
I thought we want to avoid ForgeHooks and use mixin for all events?  
Here is the mixin implementation for the same thing https://github.com/ScribbleLP/TASmod/blob/28e96e03fa63ca30caca2a984734f353387cbb2d/src/main/java/de/scribble/lp/tasmod/mixin/events/MixinNetHandlerPlayClient.java#L18

2022-02-05 21:37 UTC, MCPfannkuchenYT commented on src/com/minecrafttas/tasmod/CommonTASmod.java
> +	 * Initialize the TASmod on the launching integrated or dedicated server.
no this is correct
The TASmod should be initialized ON THE server that is about to launch.
Things such as commands have to be initialized ON the server

2022-02-05 21:38 UTC, MCPfannkuchenYT commented on src/com/minecrafttas/tasmod/client/ClientTASmod.java
> +	public void onClientConnect(ClientConnectedToServerEvent e) {
doesn't matter, but thanks anyways.

2022-02-05 21:41 UTC, ScribbleLP commented on src/com/minecrafttas/tasmod/CommonTASmod.java
> +	 * Initialize the TASmod on the launching integrated or dedicated server.
Then it should be `on the integrated or dedicated server, that is about to launch`. Because to me the current version doesn't make me understand that

2022-02-05 21:42 UTC, MCPfannkuchenYT commented on src/com/minecrafttas/tasmod/CommonTASmod.java
> +	 * Initialize the TASmod on the launching integrated or dedicated server.
👍Will do.

2022-02-05 21:48 UTC, ScribbleLP approved these changes

2022-02-05 21:48 UTC, MCPfannkuchenYT commented
Continuing with the rest now...

2022-02-05 23:59 UTC, MCPfannkuchenYT commented
The server works now, however something weird is happening. The last commit is supposed to kill the client and the server after leaving the world. Looking into the log it clearly tries to, however even after the interrupt signal the client and server continue to run.
This actually isn't a fatal issue however, when the client and server are started again the previous ones die immediately. I don't know how this happens... Maybe you find anything...

Also there is a memory leak in sendPacket() which I will fix tomorrow

2022-02-06 00:07 UTC, MCPfannkuchenYT commented
Did two small changes. 
* Fixing the memory leak
* Uncommenting the interrupt() code (which did not affect the behavior at all)
Will push tomorrow

2022-02-06 09:46 UTC, ScribbleLP approved these changes

2022-02-06 12:39 UTC, ScribbleLP approved these changes

2022-02-06 12:39 UTC, merged